### ISSUE TITLE
[websocket]WebSocket handshake Unexpected response code 403

### ISSUE THREAD

**Issue by cherishman2005** [cherishman2005/nginx-modules#62]
```
  [Symbol(kError)]: Error: Unexpected server response: 403
      at ClientRequest.<anonymous> (/data/services/webrtc/collider_tools/rtc_server/node_modules/ws/lib/websocket.js:896:7)
      at ClientRequest.emit (events.js:400:28)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
      at TLSSocket.socketOnData (_http_client.js:515:22)
      at TLSSocket.emit (events.js:400:28)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at TLSSocket.Readable.push (internal/streams/readable.js:206:10)
      at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23),
  [Symbol(kMessage)]: 'Unexpected server response: 403'
```

**Comment by cherishman2005** [comment]
https://blog.csdn.net/u014231523/article/details/102786886

**Comment by cherishman2005** [comment]
```
Can you try header like this and check

var ws = new WebSocket('wss://apiv2.unificationengine.com/v2/ws/start', {
    origin: 'https://apiv2.unificationengine.com',
    headers: { Authorization: 'base64 auth' }
});
You can create base64 auth like this in nodejs

var auth = "Basic " + new Buffer(USER_ACCESS_KEY + ":" + USER_ACCESS_SECRET).toString("base64");
```

resolve it:
```
var ws = new WebSocket('wss://***.com/v2/ws/start', {
    origin: 'https://***.com',
});
```
